matrix:
  include:
    - language: elixir
      elixir:
        - '1.7.4'
      otp_release:
        - '20.0'
      script:
        - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - language: node_js
      node_js:
        - 'node'
        - '10'
      install:
        - npm run test-i
      script:
        - npm run coverage

notifications:
  email:
    - kanon75505601@yahoo.com.tw
